apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:4d5b58dd4d0ea50c4b29d3fb4449a392dbb71a39f5ba3eb0eb334571005354b1
  name: quay.io/siamaksade/spring-petclinic:latest
  newName: image-registry.openshift-image-registry.svc:5000/cicd/spring-petclinic
